# Generated by Django 5.1.1 on 2024-09-29 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('search_keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='source',
        ),
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawlers.url'),
        ),
    ]
